/**
 * Snapshot 命令：生成專案狀態快照
 */

import fs from 'fs/promises';
import path from 'path';
import YAML from 'yaml';
import { ProjectState, SnapshotOptions } from '../types.js';
import { GitAnalyzer } from '../utils/git.js';
import { ProjectAnalyzer } from '../utils/project-analyzer.js';

export class SnapshotCommand {
  private projectPath: string;
  private gitAnalyzer: GitAnalyzer;
  private projectAnalyzer: ProjectAnalyzer;

  constructor(projectPath: string = process.cwd()) {
    this.projectPath = projectPath;
    this.gitAnalyzer = new GitAnalyzer(projectPath);
    this.projectAnalyzer = new ProjectAnalyzer(projectPath);
  }

  async execute(options: SnapshotOptions = {}): Promise<ProjectState> {
    console.log('🔍 Analyzing project...');

    // Gather all information in parallel
    const [architecture, gitState, existingState, projectName, lastAgent] = await Promise.all([
      this.projectAnalyzer.analyzeArchitecture(),
      this.gitAnalyzer.getGitState(),
      this.loadExistingState(),
      this.getProjectName(),
      this.detectLastAgent()
    ]);

    // Build project state
    const state: ProjectState = {
      meta: {
        project_name: projectName,
        last_updated: new Date().toISOString(),
        last_agent: lastAgent,
        snapshot_version: '0.1.0'
      },
      architecture,
      current_task: existingState?.current_task || this.createDefaultTask(),
      decisions: existingState?.decisions || [],
      git_state: gitState,
      context: existingState?.context || {
        important_notes: [],
        potential_issues: []
      }
    };

    // Save to file
    const outputPath = options.output || path.join(this.projectPath, 'project_state.yml');
    await this.saveState(state, outputPath);

    console.log(`✅ Snapshot saved to: ${outputPath}`);

    if (options.verbose) {
      console.log('\n📊 Summary:');
      console.log(`  Tech Stack: ${architecture.tech_stack.join(', ')}`);
      console.log(`  Key Files: ${architecture.key_files.length}`);
      console.log(`  Uncommitted Files: ${gitState.uncommitted_files.length}`);
      console.log(`  Recent Commits: ${gitState.recent_commits.length}`);
    }

    return state;
  }

  private async getProjectName(): Promise<string> {
    try {
      // Try to get from package.json
      const packageJsonPath = path.join(this.projectPath, 'package.json');
      const content = await fs.readFile(packageJsonPath, 'utf-8');
      const pkg = JSON.parse(content);
      return pkg.name || path.basename(this.projectPath);
    } catch (error) {
      // Fallback to directory name
      return path.basename(this.projectPath);
    }
  }

  private async detectLastAgent(): Promise<string | undefined> {
    // Try to detect which agent was last used
    // This is a simple heuristic based on common agent directories
    const agentMarkers = [
      { dir: '.claude', name: 'Claude Code' },
      { dir: '.cursor', name: 'Cursor' },
      { dir: '.copilot', name: 'GitHub Copilot' },
      { dir: '.aider', name: 'Aider' }
    ];

    for (const marker of agentMarkers) {
      const markerPath = path.join(this.projectPath, marker.dir);
      try {
        await fs.access(markerPath);
        return marker.name;
      } catch {
        continue;
      }
    }

    return undefined;
  }

  private createDefaultTask() {
    return {
      goal: 'No active task defined',
      status: 'pending',
      completed: [],
      next_steps: ['Define project goals', 'Set up development environment']
    };
  }

  private async loadExistingState(): Promise<ProjectState | null> {
    try {
      const statePath = path.join(this.projectPath, 'project_state.yml');
      const content = await fs.readFile(statePath, 'utf-8');
      return YAML.parse(content) as ProjectState;
    } catch (error) {
      return null;
    }
  }

  private async saveState(state: ProjectState, outputPath: string): Promise<void> {
    const yaml = YAML.stringify(state, {
      indent: 2,
      lineWidth: 100
    });

    // Add comments for better readability
    const withComments = this.addComments(yaml);

    await fs.writeFile(outputPath, withComments, 'utf-8');
  }

  private addComments(yaml: string): string {
    const header = `# Project State Snapshot
# Generated by save-my-session
# This file captures the current state of your project for seamless AI agent handoffs
#
# Usage:
#   - Review and update current_task as you work
#   - Add decisions when making important architectural choices
#   - Use 'save-my-session restore' to generate context for a new agent
#
---
`;

    return header + yaml;
  }
}
